### ISSUE TITLE
java.io.IOException:Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations'

### ISSUE THREAD

**Issue by JamesChen1202** [MindorksOpenSource/AndroidTensorFlowMNISTExample#4]
Repro steps:
1. replace mnist_model_graph.pb in app/src/main/assets with AndroidTensorFlowMNISTExample/model/
2. Run "Debug app" in Android Studio

Observed:
App crash with below log.
E/AndroidRuntime: 
FATAL EXCEPTION: pool-1-thread-1 Process: com.mindorks.tensorflowexample, PID: 3776
java.lang.RuntimeException: Error initializing TensorFlow!
 at com.mindorks.tensorflowexample.MainActivity$3.run(MainActivity.java:114)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)
 Caused by: java.lang.RuntimeException: Failed to load model from 'file:///android_asset/mnist_model_graph.pb'
 at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:100)
 at com.mindorks.tensorflowexample.TensorFlowImageClassifier.create(TensorFlowImageClassifier.java:101)
 at com.mindorks.tensorflowexample.MainActivity$3.run(MainActivity.java:104)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
 at java.lang.Thread.run(Thread.java:764) 
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](Reshape, WC1). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

Finding:
1. These 2 mnist_model_graph.pb difference in file size.
2. Is it possible that these 2 .pb file is generated by different tensorflow version causes this error?

**Comment by JamesChen1202** [comment]
I figure it out.
It turns out my ubuntu tensorflow is v1.5 but the android studio gradle using `'org.tensorflow:tensorflow-android:1.2.0'`

So i modify the gradle file to this:
`implementation 'org.tensorflow:tensorflow-android:1.5.0'`

Check tensorflow version
`
python -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 2  `
`python3 -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 3
`
